### ISSUE TITLE
scrollbars are hiding the attribution control!

### ISSUE THREAD

**Issue by Bonkles** [OvertureMaps/io-site#64] opened 2024-06-05 18:23 UTC
Right now, we have an attribution callout to both overture maps and to openstreetmap. 

the problem is that it is obscured by scrollbars! See screenshot: 

![image](https://github.com/OvertureMaps/io-site/assets/1887955/ed0b9408-3266-4b89-a59c-e9e821ea9b3c)

**Comment by jwass** [comment] 2024-06-06 01:05
@charliemcgrady asked if others are also seeing this. Happens for me too.
<img width="607" alt="Screenshot 2024-06-05 at 9 04 54 PM" src="https://github.com/OvertureMaps/io-site/assets/1214350/248ee4fb-0fca-432b-a749-0a142abd4756">

**Comment by charliemcgrady** [comment] 2024-06-06 05:33
Thanks for the screen shot @jwass, that was helpful.

Raised https://github.com/OvertureMaps/io-site/pull/65. I removed the footer for now which should remove the vertical scrollbar, but still not sure why some folks are seeing horizontal scrollbars. @jwass @Bonkles, are y'all on windows laptops by any chance?

As a stop gap, I added some padding to the attributions to make sure they are visible even if the page has horizontal scroll.

**Comment by charliemcgrady** [comment] 2024-06-06 05:40
Since I still haven't been able to reproduce would be great if someone could double check the padding is enough once merged!

**Comment by jwass** [comment] 2024-06-06 09:10
Updated to the attribution-fix branch and it looks good to me now. I'm on chrome on Sonoma

<img width="440" alt="Screenshot 2024-06-06 at 5 10 13 AM" src="https://github.com/OvertureMaps/io-site/assets/1214350/caf8729c-7850-4231-8035-21d7f6d285d0">

**Closed** 2024-06-21 15:10 UTC
