### ISSUE TITLE
Download Button UI Improvement

### ISSUE THREAD

**Issue by eti7075** [OvertureMaps/io-site#47] opened 2024-05-22 12:56 UTC
Currently, the download button is disabled while downloading takes place. This is not the best user experience, as the download can take a long time. Instead, the download icon should be changed to a rotating spinner so that it is clear to the user that the download is in progress, providing a better experience.

**Comment by charliemcgrady** [comment] 2024-05-22 15:49
I believe this is a duplicate of https://github.com/OvertureMaps/io-site/issues/24. There are a couple of download button related issues:
- https://github.com/OvertureMaps/io-site/issues/35
- https://github.com/OvertureMaps/io-site/issues/22

Would be a good idea to have someone tackle all these at once

**Comment by eti7075** [comment] 2024-05-22 16:54
Interesting. Ben asked me to create a new issue to get practice, but I guess we missed the duplicate. I'll close this as a duplicate and switch to the original. I can definitely start to look into those other issues as well.

**Closed** 2024-05-22 16:54 UTC
